name: tooth_care_app
description: Tooth care Flutter app frontend
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  android_alarm_manager_plus: ^5.0.0
  android_intent_plus: ^5.1.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  fl_chart: ^0.66.2
  url_launcher: ^6.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO1.jpg
    - assets/LOGO2.jpg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/LOGO1.jpg
  min_sdk_android: 21